<script setup>
import CategorySelect from '../components/CategorySelect.vue';
</script>
<template>
  <div>
    <div class="py-2 px-6">
      <button
        type="button"
        class="pb-6 text-white text-2xl font-semibold hover:underline cursor-pointer"
      >
        Browse All
      </button>
      <div
        class="grid 3xl:grid-cols-7 xl:grid-cols-5 lg-grid-cols-4 md:grid-cols-3 gap-x-3 gap-y-3"
      >
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
        <CategorySelect
          category="Podcasts"
          width="194"
          height="194"
          image="https://picsum.photos/id/101/300/300"
        />
      </div>
    </div>
  </div>
</template>
